const POST_ACTION_TYPES = {
    SET_UPDATED_POST: 'post/SET_UPDATED_POST',
    SET_POST_ITEMS: 'post/SET_POST_ITEMS',
    SET_NEW_POST: 'post/SET_NEW_POST',
    SET_DELETE_POST: 'post/SET_DELETE_POST'
};

export default POST_ACTION_TYPES;