const POST_ACTION_TYPES = {
    SET_UPDATED_POST: 'post/SET_UPDATED_POST',
    SET_POST_ITEMS: 'post/SET_POST_ITEMS',
    SET_POST_ITEM: 'post/SET_POST_ITEM',
    SET_POST_ITEMS_BY_SEARCH: 'post/SET_POST_ITEMS_BY_SEARCH',
    SET_NEW_POST: 'post/SET_NEW_POST',
    SET_DELETE_POST: 'post/SET_DELETE_POST',
    START_LOADING:  'START_LOADING',
    END_LOADING:  'END_LOADING'
};

export default POST_ACTION_TYPES;